name: Create RPM and DEB packages on release                                                        
                                                                                   
on:
  release:                                                                         
    types: [created]       

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

  build-deb:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get cASO repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      
      - name: Copy debian file into the correct place for the build
        run: cp -r packaging/debian debian

      - name: Build Debian package
        uses: alvarolopez/action-debian-python-package@v3
        with:
          artifacts_directory: output
          os_distribution: stable

      - name: Update DEB artifacts to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'output/*deb'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
  
  build-rpm:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get cASO repo
        uses: actions/checkout@v3
        with:
          repository: IFCA/caso
          ref: ${{ github.ref_name }}
      
      - name: Build sdist to use as source
        run: python setup.py sdist

      - name: Build RPM package
        id: rpm
        uses: alvarolopez/rpmbuild@rockylinux8
        with:
          source_file: dist/caso-${{ github.ref_name}}.tar.gz
          spec_file: "packaging/redhat/caso.spec"

      - name: Update RPM artifacts to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '${{ steps.rpm.outputs.rpm_dir_path }}/*/*rpm'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
